# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "./custom_download_strategy.rb"
class DbtHelper < Formula
  desc "dbt-helper"
  homepage "https://github.com/Big-Time-Data/dbt-helper"
  version "0.0.12"
  depends_on :macos

  url "https://github.com/Big-Time-Data/dbt-helper/releases/download/v0.0.12/dbt-helper_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
  sha256 "4ddbebb6278f1cfb72fa9f62f7992cc744578126aea70f9423835b92ff89b11e"

  def install
    bin.install "dbt-helper"
  end

  if Hardware::CPU.arm?
    def caveats
      <<~EOS
        The darwin_arm64 architecture is not supported for the DbtHelper
        formula at this time. The darwin_amd64 binary may work in compatibility
        mode, but it might not be fully supported.
      EOS
    end
  end
end
