# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DbtHelper < Formula
  desc "dbt-helper"
  homepage "https://github.com/Big-Time-Data/dbt-helper"
  version "0.0.18"
  depends_on :macos

  url "https://github.com/Big-Time-Data/homebrew-dbt-helper/releases/download/v0.0.18/dbt-helper_darwin_amd64.tar.gz"
  sha256 "65a6f27f6edb9c380989178a34f531448ecfb639f62ba9e51c19b96092d2486e"

  def install
    bin.install "dbt-helper"
  end

  if Hardware::CPU.arm?
    def caveats
      <<~EOS
        The darwin_arm64 architecture is not supported for the DbtHelper
        formula at this time. The darwin_amd64 binary may work in compatibility
        mode, but it might not be fully supported.
      EOS
    end
  end
end
